### ISSUE TITLE
Updating to use Lucee?

### ISSUE THREAD

**Issue by howellcc** [foundeo/ubuntu-nginx-railo#1]
Will you be updating these scripts to use Lucee now that it doesn't appear that Railo will continue?

**Comment by pfreitag** [comment]
Yes, planning on updating it to use Lucee. Not sure if I will create a new repository or just update this one yet.

**Comment by JasPanesar** [comment]
I think it'd be fine to update the existing one.  Thanks for your work on these

**Comment by howellcc** [comment]
Awesome! Thank you for the quick reply.
